spring:
  application:
    name: solr-sample
  docker:
    compose:
      lifecycle-management: start-and-stop
      readiness:
        wait: always
  solr:
    host: http://localhost:8983/solr
    default-collection: books
    commit-mode: immediate

management:
  endpoints:
    web:
      exposure:
        include: health
  health:
    solr:
      enabled: true
